title: Marina Gul
email: marina.gul@iba-suk.edu.pk
logo: /assets/img/logo.png
description: #Data Scientist
  
url: "https://marina-gul.github.io/portfolio" # Your website URL

show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

author:
  name: Marina Gul
  email: marina.gul@iba-suk.edu.pk
  bio: Hi, I'm **Marina**, a computer scientist and researcher specializing in big data clustering, NLP, and AI applications. This site showcases my projects and research.
  location: Khairpur, Pakistan
  github: https://github.com/Marina-Gul
  linkedin: www.linkedin.com/in/marina-rajput-6228156b
